name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools (Ubuntu/macOS)
        if: runner.os != 'Windows'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build
      - name: Set up MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure (CMake)
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --parallel

      - name: Run --version
        if: runner.os != 'Windows'
        run: ./build/morsewav "--version"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: morsewav-${{ runner.os }}
          path: |
            build/morsewav${{ runner.os == 'Windows' && '.exe' || '' }}

  sanitize-linux:
    name: Sanitizers (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build
      - name: Configure with sanitizers
        run: cmake -B build -G Ninja -DENABLE_SANITIZERS=ON -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build --parallel
      - name: Run with sanitizers
        run: ./build/morsewav "--version"

  clang-tidy:
    name: clang-tidy (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-tidy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-tidy ninja-build
      - name: Configure compile_commands.json
        run: cmake -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run clang-tidy
        run: |
          clang-tidy -p build $(git ls-files '*.c' | tr '\n' ' ')
