name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build clang-tidy cppcheck

      - name: Configure (CMake)
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Build
        run: cmake --build build --parallel

      - name: Run --version
        run: ./build/morsewav -V

      - name: Run clang-tidy
        run: clang-tidy -p build $(git ls-files '*.c' | tr '\n' ' ')

      - name: Run cppcheck
        run: cppcheck --enable=warning,style,performance,portability --suppress=missingIncludeSystem $(git ls-files '*.c' | tr '\n' ' ')

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: morsewav-${{ runner.os }}
          path: |
            build/morsewav${{ runner.os == 'Windows' && '.exe' || '' }}




